title: 'ServerlessSpy'
project: 'ServerlessSpy'
description: 'CDK-based library for writing elegant integration tests on AWS serverless architecture and an additional web console to monitor events in real time.'
keywords: 'serverless-spy, serverlessspy, cdk, aws, integration testing, testing, jest, serverless'
author: Marko (ServerlessLife)
email: marko@serverlesslife.com
image: https://serverlessspy.com/logo/logo.png
twitter_username: ServerlessL
twitter:
  username: ServerlessL
  card: player cards
og_image: https://serverlessspy.com/logo/logo.png
github_username: serverlesslife
show_downloads: false
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true # Auto-generate ID's for headings
future: true
jailed: false
gfm_quirks: paragraph_end
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
teaser: https://serverlessspy.com/logo/logo.png
logo: https://serverlessspy.com/logo/logo.png
markdown: kramdown
sass:
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/
exclude:
  - node_modules
  - test/node_modules
  - vendor
repository: ServerlessLife/serverless-spy
baseurl: /
include:
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE.md
analytics:
  provider: 'google-gtag'
  google:
    tracking_id: 'G-C2PHH6WYPP'
social:
  links:
    - 'https://twitter.com/ServerlessL'
    - 'https://www.linkedin.com/in/marko-serverlesslife/'
author:
  name     : Marko (ServerlessLife)
  avatar   : "/logo/marko_serverlesslife.jpg"
  bio      : "Full-stack Software Developer | AWS Certified Professional | Serverless Specialist"
